### ISSUE TITLE
Error '$global:OPDStrings'

### ISSUE THREAD

**Issue by joananms** [onpremdiag/SharePoint#2]
Hi,

How i can resolve this issue?

![image](https://user-images.githubusercontent.com/12891938/66313064-03909180-e912-11e9-9422-175f06d64d1c.png)

Thanks!

**Comment by onpremdiag** [comment]
@joananms - Thanks for bringing this to our attention. We are currently investigating. Can you provide me with some additional information?

1. What is the OS that you are running OPD on?
2. Is SharePoint installed on that machine?
3. Which release of OPD are you running?

**Comment by onpremdiag** [comment]
Root cause determined (AB#25466)
Attempting to load a localized resource file (CommonStrings.??-??.resx) and it did not exist. Next, we were attempting to write an event in the event log which referenced a value not yet in scope. This has been corrected.

**Comment by onpremdiag** [comment]
Updated release is now available. Please download. Let us know if you have any other issues.

Thanks,
opd-support@microsoft.com
